name: AutoXP
main: JackMD\AutoXP\Main
api: [3.0.0]
version: 1.0.2
author: JackMD
load: POSTWORLD
description: Say goodbye to xp orbs, now they come directly to your inventory.
website: https://github.com/JackMD/AutoXP
